### PR TITLE
update reminders.php. The password is required 'at least'

### PR DESCRIPTION
**Pull request by zhuzhichao**
The password is required 'at least', but here 'at least' isn't translated.

### CODE REVIEW

**Comment by overtrue** [comment]
@zhuzhichao is right.

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Auth/Passwords/PasswordBroker.php#L221

:+1:

**Comment by overtrue** [comment]
@zhuzhichao 建议修改文字 “必须至少” 为 “至少”

**Comment by caouecs** [comment]
Thanks, and it's good for laravel5 branch ?

**Comment by overtrue** [comment]
@caouecs yes!

**Pull request merged**
