### PR TITLE
update validation.php in zh-CN and zh-HK, fix the translation error about 'exist'

### PR DESCRIPTION
**Pull request by keeword**
update validation.php in zh-CN and zh-HK, fix the translation error about 'exist'

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
for zh, I prefer to wait after @overtrue

**Comment by overtrue** [comment]
Hi, @caouecs, Here indeed misunderstood, and he is correct changes. :+1:

**Comment by overtrue** [comment]
@keeword 谢谢指正！

**Comment by keeword** [comment]
:smiley:

**Comment by caouecs** [comment]
Thanks

**Pull request merged**
